application:
  object-storage:
    CHARSET_NAME : ENC(U4Noslx7ZHq9rzBtf6dOkvHjHrdMC468edWHDGaMmWn7z3TPVJ05h3MMxNpcYfgK)
    HMAC_ALGORITHM : ENC(HG7UWC8+Z+5FmX+/j8i3vALuMLlm0o9YJtizilsYuN8ebvbuZZpShSiXN8Nm1TL+)
    HASH_ALGORITHM : ENC(N2rSjY4UgKXZyAbleROcynahmZsZIICMdAdn7fYbUbdzSwn9KjMFo5GsyvUSvGLv)
    AWS_ALGORITHM : ENC(1fufspy1E1oxIDJmfwBAM44lnVbY/NbBYs/NzskR2XO0dj4LufkCYogia/IFcF7cvVGpI6UQq9KTDWMgw5Tq7Q==)

    SERVICE_NAME : ENC(OpDrU3hTdZKNVVzG7lJvdtJpfvYUdC1F7dHlg7XLIziCKh3xh1OLe66UuY7OOtZa)
    REQUEST_TYPE : ENC(C7fdzk7O5Bwrp4KxhKgAc5PSQwFz5EV9LYKZMt2oaSedt0AOV9+cWJNcUM9cnKPI)

    UNSIGNED_PAYLOAD : ENC(HJGUISNOrW94O5lUqeYyEDRqxW+OiPzOClo92wD0hjtgwuywEMZZCqHNv/I07IHIQnxSdW4h2iPOZ1U6eg0XGw==)

    # Central resion
    REGION_NAME : ENC(jATsEhW9zE8/pcjfwxA+iv8meKzhZbT87zRNg71bdcMzncjBANTrJOsnbrfYQNn2)
    ENDPOINT_SEOUL : ENC(fiyqcuSODjgt5+lqpsZiuLiTlu0w1yGZ/CEa6QjsgJfpKSe0IHYzBC2C7iMWKXe8KIZlNubjUgCnKAGo/5JHQlcZW4R7M0B880Xumam20+0=)
    ENDPOINT_SOUTH : ENC(5hHpDT7+AdXllsZyvMkO4OtrqXPSNBYgTZeT8uA0qEWFVHzcMLi6gTzfCD4CQIOcp34C6QQI3ejuY/08MBJIVDcUMowzdrrihY1qvgHSN0g=)
    ACCESS_KEY : ENC(Ee1o7PVw70AMHEJknXUjNLy67L/3SSfBj7LT9V+yN2GOLN/hgYIQg+rNSyalLvvVzkJ3S3RwdsNlgwzaVoorHw==)
    SECRET_KEY : ENC(Y/RXJAtj8jPM0VfLADwPEW4CJ38PG1ua1H7Rk9Dt4go8BKM+RPokmq5E+PYsNyT1XfvllHwq2bs4jUkkyCHaHMs2V5zAA8BsUjuz0q6Wh1k=)

jasypt:
  encryptor:
    bean: jasyptEncryptorAES
#    password: ez-psm-saas

spring:
  application:
#    name: ${APP_NAME}
    name: backup-manager
  profiles:
    active: dev
  # datasource
  portal:
    datasource:
      hikari:
        driver-class-name: ENC(PVcCSf7RvQqVe/IYcx/KWt2Q6LnJ5KEUQX2XXbTy/ALTifxRAs9ba3h+HuGgCxCT2Wf1oYPQb1i3kP1NF415Ow==)        
        jdbc-url: ENC(0MrjBojzCqtfidAeWdlM2xS+GQEePgeIhleP9bpUzGtYg8eXVusaX75V0MYLS7KfiKoeqpcd4tiEM0RZcTa7QU4IvOmsT9Jhl7DvrnxNfl7/G2NGb7GTa8u4iPxFVmmuNCZ5YhZrIMzvEICjKMr68sSC8GdZER1WXG3Ge+3jOhk=)
        username: ENC(n7kbzMSiSbWGZru99M2haghOcZnap0kBWPGUVkM4HUnQQU39ubQ6Go0tmZNHIRZ5)
        password: ENC(t8+XQqKsH6JKqty2N0T5DlRB8DxlnisJ+jo865l+q468zkUP+T0hGxIE+hEGIZeh)
        pool-name: ENC(r9YGyZp01089DSdnLORQnI+p2BRoklEHcfdI2fqW1lAOPTVVGR0s60R29Pyg+B/uDiQ1f2k3KL9V6wO/1A73Jg==)
        # auto-commit: false
        # connection-test-query: SELECT 1
        # transaction-isolation: TRANSACTION_READ_UNCOMMITTED
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 1
        max-lifetime: 15000
        maximum-pool-size: 10        
        # multi-rows insert option
        data-source-properties: 
          reWriteBatchedInserts: true
  user:
    datasource:
      hikari:
        driver-class-name: ENC(PVcCSf7RvQqVe/IYcx/KWt2Q6LnJ5KEUQX2XXbTy/ALTifxRAs9ba3h+HuGgCxCT2Wf1oYPQb1i3kP1NF415Ow==)        
        jdbc-url: ENC(bakBb8jqc95XSS5vDqv4erOoClZbJAw4Y6xZjSfSdOwgtD9fC4i3Myt3TK3OSeh0sKDg5rqqbdBBMQNPCjw59SalxtjBSmFWEEXQPZgmhKma3pPgREffegJd1qDH0uWAF+dEmd975hBqJkKuoJ9R0/VhZ5vfuHkVAL1N4+Y19RI=)
        username: ENC(BKdnWfzOf8msob8jije3hqS+hs21pSsoHtxujByiECHYZDeJrhSgWxuULU3Vd3nz)
        password: ENC(4AAHx3tgCipsfg2XFdMZd8FGo/9r51rZ8ofj695N0ojTqV5dYIdULc635Hi+tSce)
        pool-name: ENC(6G6W/gdGnvKWlvb+bGRbma79Vlx/RRyUo3XcCf1FTwWe6RF3QKuPBFBCUmphTVyjWZo7W6HqOQfxWUqXpbLG7A==)
        # auto-commit: false
        # connection-test-query: SELECT 1
        # transaction-isolation: TRANSACTION_READ_UNCOMMITTED
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 1
        max-lifetime: 15000
        maximum-pool-size: 10
        # multi-rows insert option
        data-source-properties: 
          reWriteBatchedInserts: true
#logging:
##  config:
#  level:
#    com:
#      error
#  file: 
#    path: /${spring.application.name}/logs
#    name: error.log
---
# local
spring:
  config:
    activate:
      on-profile: local
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  etc:
    DIR_PATH: /home/naru/temp/temp
    LOG_PATH: /backend-sys/backup-scheduler
    # script naems
    LOG_SCRIPT: backup_log.sh    
    SCHEMA_SCRIPT: backup_schema.sh
    # cron scheduler
    SCHEDULE_TIME: "0 0 1 * * *"

---
# dev
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html 

application:
  etc:
    # script location
    DIR_PATH: /app/util
    # log location
    LOG_PATH: /app/logs/schema/${COMPANY}/${APP_NAME}
    # script naems
    LOG_SCRIPT: backup_log.sh    
    SCHEMA_SCRIPT: backup_schema.sh
    # cron scheduler
    SCHEDULE_TIME: "0 0 1 * * *"
---
# prod
spring:
  config:
    activate:
      on-profile: prod

application:
  etc:
    # script location
    DIR_PATH: /app/util
    # log location
    LOG_PATH: /app/logs/schema/${COMPANY}/${APP_NAME}
    # script naems
    LOG_SCRIPT: backup_log.sh    
    SCHEMA_SCRIPT: backup_schema.sh
    # cron scheduler
    SCHEDULE_TIME: "0 0 1 * * *"
    
      
