application:
  object-storage:
    CHARSET_NAME : ENC(Pb4K3bwqBDVVx8doHTijhA1gEJH3/OLVx8SVmPPe9R366k4gyABUibhWJBru2BAc)
    HMAC_ALGORITHM : ENC(DBEyaewCc06MGVrtzrf5TctjxK356w/XVrhFggQfZyNDfcccIl3lG7p45Qmz7iYc)
    HASH_ALGORITHM : ENC(7/HoczhyYCwPLpr6aB5y/9TmLpo+H0n+eC5YTg6ZR8LBteEbcGKUVCJZYKzDbr+E)
    AWS_ALGORITHM : ENC(CQcG8kqbg/mDzzrSYnqDU46/ZhurcoZnrcyksMTXbsW3m7JTv7Iccq7fOvZwMgzP3T7BcnsAsSA3bYE3muZQIA==)

    SERVICE_NAME : ENC(U+/Y+y9oEYI/zupvquRmPlPr+LK/R+Fyba7YKaHCE9YWGsf9ODLmccgsBAEjUmQi)
    REQUEST_TYPE : ENC(80jHO91U6k98qYKkaYlywyAOjkPZsJ3c6igEwJUzFa0zPbK9kPXRqeLm6qvghCuw)

    UNSIGNED_PAYLOAD : ENC(pGIo+HZGryv/DdCilsPRQMAkgmdOvtv2YkZvk/SAzhKP3G43pbJ898TyxiU7IdXHMa150O7M15pKrRDRXKf7ZA==)

    # Central resion
    REGION_NAME : ENC(H2+1s4qMBbrg70GgwxlS7zpYPjKJKrDtzIEWbJswmX6FcaT0vJSsOswYittd1VOz)
    ENDPOINT_SEOUL : ENC(tQoyrzhE3bH7lLd/B6UAXvzAsZZtC31FRe1mDQ0+CsXEFYmJ6qWKUBLK02d29lC2dZYa6rgyraPScmTUloFw3ax8oOr62aVC0AtHMdT4fKE=)
    ENDPOINT_SOUTH : ENC(ImX6mLxeIBABu0hB+sGH8ocTEy2TCSth7FT+jrDnCjULmCpdzqvR2HKZk8/o8xYYx7pFU23Xb3TZKbPVXCC5hLeaUdcT/15rqHQvcNduZUE=)
    ACCESS_KEY : ENC(a3ya3bRrP+dWQkm+u99DvYkJWhijRXBRj3nIngKF3GV7UvzNVLItpMhUywjQXy5g8zFl30RCJrq19n6Y2cgGhQ==)
    SECRET_KEY : ENC(qoPGifIVFj6rsa+nY/zYp1ZrSe3PZr560uAPXziHYq6eVJMCkVQO65RoNIJXBr5dM4EjmVJXr31ZUYctBf+vLJGCwKd8D1Ovj+dPnExKbrw=)
    
    # aws client v2
    AWS_PATH: /usr/local/bin/aws
    SYNC_BUCKET_COMMAND: "--endpoint-url=<objecturl> s3 sync s3://<source> s3://<destination>"

jasypt:
  encryptor:
    bean: jasyptEncryptorAES
#    password: ez-psm-saas

spring:
  application:
#    name: ${APP_NAME}
    name: backup-manager
  profiles:
    active: prod
  # datasource
  portal:
    datasource:
      hikari:
        driver-class-name: ENC(sA7TFX4KYqOtvBfHmv5Yx/vRRVR2X878F+ddY1GZQ5ymjQj+kDHRkSEzMEE7WDmXtpW0JgV0/z2uYIzWug7gWg==)        
        jdbc-url: ENC(4HrLGQaDfodOeavT8p1lDLUbiL24qTcYXsjIAOFCtoqGhanN2WDKU5tqYHvQRxZ5eLUE9deAnLK2/38yd0CKQ8Hltr0gf/cMHGAEAUkpNTonhUmBEchd0DZB8zwNCLmtaxg8xvDIFTI3OKopiVFm1Q==)
        username: ENC(eUUU1ouTDKqclt+7ztK36ir+tOesZW+F4PXo4eCKifo6pfkoLVphwSAA4iYGnkOi)
        password: ENC(uzVLoZHjaqSJ1e95SM9ksDCR4HI5Hy0Q8xJP+jv9HOHwHhWWBdy/bkybdYaUJxzj)
        pool-name: ENC(k8zexv6I8EIh9fcd/l/51lXj7YphueUaLcbfyz15cuRwgFZDVnEDANXI6YVrpn7O2IakT2k2PQglBAOX8QzCqA==)
        # auto-commit: false
        # connection-test-query: SELECT 1
        # transaction-isolation: TRANSACTION_READ_UNCOMMITTED
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 1
        max-lifetime: 15000
        maximum-pool-size: 10        
        # multi-rows insert option
        data-source-properties: 
          reWriteBatchedInserts: true
  user:
    datasource:
      hikari:
        driver-class-name: ENC(sA7TFX4KYqOtvBfHmv5Yx/vRRVR2X878F+ddY1GZQ5ymjQj+kDHRkSEzMEE7WDmXtpW0JgV0/z2uYIzWug7gWg==)        
        jdbc-url: ENC(KI7TMeDtzn5dNv9J1wpitGQzALc7TE2b/xQ6kqg+bGkWUdxCBcNXKWwqymCRxn8TmZJsdwXsTYflkRB5z2P61sbdnCA5+Nt9RYtfbRCq6PPEphWESRdUiKP5B2Zr//2S)
        username: ENC(G/7jX+WXSU8rnQ9FOS/qgxJpZIgYsDGuMk+4XA18p/EDB7hkpkT4jYxQMJzg/mgL)
        password: ENC(gi5aiEATevLePrqRgLNbZUZEvUtKOHpeIP2YB13V2UbzHt+ZYkq6Hz9Ta6QptxKv)
        pool-name: ENC(yAwhCVWbhUa7WQ/KFuNGRJPT2mUmXbBfrd/nu/Eqwrv015WmrYuqjs1Np/ZEar77yQyBLTMkx5VoELreTEL4fA==)
        # auto-commit: false
        # connection-test-query: SELECT 1
        # transaction-isolation: TRANSACTION_READ_UNCOMMITTED
        connection-timeout: 3000
        validation-timeout: 3000
        minimum-idle: 1
        max-lifetime: 15000
        maximum-pool-size: 10
        # multi-rows insert option
        data-source-properties: 
          reWriteBatchedInserts: true
#logging:
##  config:
#  level:
#    com:
#      error
#  file: 
#    path: /${spring.application.name}/logs
#    name: error.log
---
# local
spring:
  config:
    activate:
      on-profile: local
      
springdoc:
  swagger-ui:
    path: /swagger-ui.html

application:
  etc:
    DIR_PATH: /home/naru/temp/temp
    LOG_PATH: /backend-sys/backup-scheduler
    # script naems
    LOG_SCRIPT: backup_log.sh    
    SCHEMA_SCRIPT: backup_schema.sh
    # cron scheduler
    SCHEDULE_TIME: "0 0 2 * * *"

---
# dev
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    path: /swagger-ui.html 

application:
  etc:
    # script location
    DIR_PATH: /app/util
    # log location
    LOG_PATH: /app/logs/schema/${COMPANY}/${APP_NAME}
    # script naems
    LOG_SCRIPT: backup_log.sh    
    SCHEMA_SCRIPT: backup_schema.sh
    # cron scheduler
    SCHEDULE_TIME: "0 0 1 * * *"
---
# prod
spring:
  config:
    activate:
      on-profile: prod

application:
  etc:
    # script location
    DIR_PATH: /app/util
    # log location
    LOG_PATH: /app/logs/schema/${COMPANY}/${APP_NAME}
    # script naems
    LOG_SCRIPT: backup_log.sh    
    SCHEMA_SCRIPT: backup_schema.sh
    # cron scheduler
    SCHEDULE_TIME: "0 0 1 * * *"
    
      
